import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nanumSquare = localFont({
  src: [{
    path: "./fonts/NanumSquareL.ttf",
    weight: "100 300",
    style: "normal",
  }, {
    path: "./fonts/NanumSquareR.ttf",
    weight: "400 600",
    style: "normal",
  }, {
    path: "./fonts/NanumSquareB.ttf",
    weight: "700 800",
    style: "normal",
  }, {
    path: "./fonts/NanumSquareEB.ttf",
    weight: "900",
    style: "normal",
  }],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nanumSquare.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
